### ISSUE TITLE
Site not Reachable

### ISSUE THREAD

**Issue by ritwik12** [MentorsWithoutBorders/mwb-website#1]
www.mentorswithoutborders.net/ is not accessible anymore.

**Comment by edmondpr** [comment]
This is currently an issue only in India and Pakistan, it's possible that I need to change the hosting provider. In the meantime you can use this Chrome extension: https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp
