### ISSUE TITLE
https://www.mentorswithoutborders.net/ is not working

### ISSUE THREAD

**Issue by viveksharmaui** [MentorsWithoutBorders/mwb-website#2]
Hello members ,
https://www.mentorswithoutborders.net/ is not reachable please try to fix this issue or if you need any help feel free to ask me .
I'm software developer from Pakistan i have experienced with Developement and Deployment .
Thanks !

**Comment by edmondpr** [comment]
This is currently an issue only in India and Pakistan, it's possible that I need to change the hosting provider. In the meantime you can use this Chrome extension: https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp

**Comment by viveksharmaui** [comment]
Use AWS because it provides one of the best services.
