### ISSUE TITLE
Add : Vivek Anand as Community Manager

### ISSUE THREAD

**Issue by viveksharmaui** [MentorsWithoutBorders/mwb-website#3]
Hello 🙌
I am first Community Manager of Pakistan and I think we should add community manager in website by creating a new page for them .
@edmondpr what you think ?

**Comment by viveksharmaui** [comment]
If yes then i can sent a PR of this issue.

**Comment by edmondpr** [comment]
That's a good suggestion but we'll have to get back to it when I'll have more time to manage the development of the new website (for which this repository was created). Closing the issue for now.
